/**
 * Founder-authored Called Name descriptions, preserved from
 * olsonan26/LOOKS-LIKE-COSTAR/services/calledNameDescriptions.ts at
 * 023140de4ac9ebad8a804b4c984337135e77b19a.
 *
 * The source intentionally has a distinct table for how other people may
 * perceive a called name. Do not substitute name-number meanings here.
 */
export const calledNameDescriptions: Record<number, { title: string; full: string }> = {
  1: { title: "The Leader", full: "People see you as a natural leader, someone who steps up and takes charge without needing to be asked. They notice your initiative and your ability to solve problems creatively, seeing you as the person who can find a path forward even when things seem blocked. They perceive you as quick-minded and confident, though they might also sense that your speed can sometimes outpace your experience, making you seem a bit headstrong. Overall, you project an aura of competence and independence that inspires others to follow your lead." },
  2: { title: "The Diplomat", full: "Others experience you as a calm and considerate presence, the person who brings a sense of quiet stability to a group. They value your incredible eye for detail and your patience, often relying on you to catch the things everyone else has missed. Because you're so thorough, some might see your pace as slow, but they quickly learn it's just your commitment to getting things right. You come across as a natural diplomat and a thoughtful listener, someone who can see both sides of a situation. People feel safe sharing their thoughts with you because they sense your gentle and analytical nature." },
  3: { title: "The Expressor", full: "People are drawn to your bright and creative energy. They see you as an expressive and imaginative person who can light up a room with your words, ideas, and sense of humor. You're perceived as a natural storyteller, able to paint a picture with your words and make complex ideas feel clear and exciting. Because of your vibrant personality, you're the person others look to for fun and social connection. While they enjoy your sparkle, they may also notice your sensitivity, seeing that you can feel things deeply and might need space when under pressure." },
  4: { title: "The Builder", full: "People see you as the reliable, hands-on person they can always count on. They notice your strong work ethic and your practical approach to getting things done, trusting you to build things that last. You come across as loyal and sincere, a true team player who will be there for friends and family without question. While you have a serious and focused side at work, others also see your fun-loving nature when you relax. They learn quickly that appreciation and kindness go a long way with you, and they know that you remember both loyalty and unfairness with equal clarity." },
  5: { title: "The Catalyst", full: "Others see you as an incredibly versatile and adaptable person, the one who can juggle multiple tasks and connect with anyone. Your energy is engaging, and you come across as a natural communicator, making you great in social or public-facing roles. People are drawn to your wide range of experiences and your ability to think on your feet. They might also notice that you have so many interests that you can sometimes get sidetracked. Under pressure, they may sense you trying to talk your way out of a tight spot, but for the most part, they see you as a resourceful and dynamic individual." },
  6: { title: "The Steward", full: "People look to you as a responsible and capable manager of situations. They see your natural ability to bring order to chaos and to guide people effectively. You come across as a caring and direct leader who isn't afraid to make sure things are done right. Your strong will is perceived as a strength, though some may find it a bit bossy if they don't understand your vision. Overall, others see you as the person to call when a steady hand is needed to manage a project, a team, or a difficult situation." },
  7: { title: "The Analyst", full: "Others often perceive you as a deep and analytical thinker with a quiet, reserved nature. They may not know what's going on inside your head, but they sense that you are observing and evaluating things on a level most people miss. You come across as someone who values quality and truth over superficial chatter. Because you need space to process, some might see you as distant or aloof, but those who get to know you appreciate your sharp mind and the well-researched knowledge you share. They see you as a specialist, the person with the refined insights." },
  8: { title: "The Powerhouse", full: "People see you as a strong, determined, and incredibly capable individual. You project an aura of authority and control, and others naturally see you as someone who can take charge of big projects and deliver results. They notice your direct, no-nonsense attitude and your willingness to work hard to achieve your goals. While you seem unshakable on the outside, those close to you may sense that you hold stress internally, as you don't often show vulnerability. You are perceived as a powerful force, a natural executive who can assess situations and people with sharp accuracy." },
  9: { title: "The Humanitarian", full: "Others see you as a compassionate and big-hearted person with a broad, understanding view of the world. They are drawn to your caring nature and your ability to connect with people from all walks of life. You come across as a gentle leader, someone who can manage things effectively while still considering the good of the whole group. People feel you are fair and trustworthy, and they appreciate your holistic approach. They see your potential to make a large, positive impact, as long as your generous spirit remains focused on collective good rather than personal gain." }
};

const rootValue = (value: number) => (value === 11 ? 2 : value === 22 ? 4 : value === 33 ? 6 : value);

export function calledNameMeaningFor(value: number): { title: string; full: string } {
  return calledNameDescriptions[rootValue(value)] ?? {
    title: "Unmapped",
    full: "Founder-authored Called Name interpretation is not available for this value."
  };
}
